Hades-Label-Act = Act
Hades-Label-Agenda = Agenda
Hades-Label-Asset = Asset
Hades-Label-Enemy = Enemy
Hades-Label-Event = Event
Hades-Label-Location = Location
Hades-Label-Skill = Skill
Hades-Label-Story = Story
Hades-Label-Treachery = Treachery
Hades-Label-Weakness = Weakness
Hades-Label-BasicWeakness = Basic Weakness
Hades-Label-Customizable = Upgrades
Hades-Label-CampaignGuide = Campaign Guide
Hades-Label-Key = Key

Hades-IllustratorShort = Illus.
Hades-Resolution-tag = <ahf>e</ahf><hdr>R
Hades-ResolutionSmall-tag = <ahf><size 80%>e<size 125%></ahf><hdr>R
Hades-Scenario-Header = DO NOT READ\n<size 80%>until the end of the scenario<size 125%>
Hades-Scenario-Header1 = DO NOT READ
Hades-Scenario-Header2 = until the end of the scenario
Hades-Guide-Standalone = Standalone Mode
Hades-Guide-Keys = Keys

Hades-Difficulty-Front = EASY / STANDARD
Hades-Difficulty-Back = HARD / EXPERT
Hades-Difficulty-Unique = EASY/STANDARD/HARD/EXPERT

Hades-DeckSize-format = <hdr>Deck Size\: </hdr>
Hades-DeckSize-formatEnd=.
Hades-SecondaryClass-format = <hdr>Secondary Class Choice\: </hdr>
Hades-DeckOptions-format = <hdr>Deckbuilding Options\: </hdr>
Hades-DeckRequirements-format = <hdr>Deckbuilding Requirements</hdr> (do not count toward deck size)\: 
Hades-DeckRestrictions-format = <hdr>Deckbuilding Restrictions\: </hdr>
Hades-AdditionalRequirements-format = <hdr>Additional Requirements: </hdr>

Hades-Prey-tag = <hdr>Prey --</hdr>
Hades-Spawn-tag = <hdr>Spawn --</hdr>
Hades-Revelation-tag = <hdr>Revelation --</hdr>
Hades-Forced-tag = <hdr>Forced --</hdr>
Hades-Objective-tag = <hdr>Objective --</hdr>
Hades-Haunted-tag = <hdr>Haunted --</hdr>
Hades-Shift-tag = <hdr>Shift --</hdr>

Hades-Keyword-Alert = Alert
Hades-Keyword-Aloof = Aloof

Hades-Keyword-Bonded = Bonded
Hades-Keyword-Bonded-Format = Bonded ({Text:Text:Text})

Hades-Keyword-CampaignOnly = Campaign only
Hades-Keyword-CampaignOnly-Format = Campaign mode only

Hades-Keyword-Concealed = Concealed
Hades-Keyword-Concealed-Format = Concealed {Amount:Word:Amount}

Hades-Keyword-DeckOnly = Deck only
Hades-Keyword-DeckOnly-Format = {Text:Text:Text} deck only

Hades-Keyword-Elusive = Elusive
Hades-Keyword-Exceptional = Exceptional
Hades-Keyword-Fast = Fast
Hades-Keyword-Hidden = Hidden
Hades-Keyword-Hunter = Hunter
Hades-Keyword-Limit = Limit
Hades-Keyword-Limit-Format = Limit {Text:Text:Text}
Hades-Keyword-Massive = Massive

Hades-Keyword-Mirage = Mirage
Hades-Keyword-Mirage-Format = Mirage {Amount:Word:Amount}

Hades-Keyword-Myriad = Myriad
Hades-Keyword-Partner = Partner
Hades-Keyword-Peril = Peril
Hades-Keyword-Prey = Prey
Hades-Keyword-Prey-Format = Prey ({Text:Text:Text})
Hades-Keyword-Patrol = Patrol
Hades-Keyword-Permanent = Permanent

Hades-Keyword-PurchaseDeckCreation = Purchase deck creation
Hades-Keyword-PurchaseDeckCreation-Format = Purchase only at deck creation

Hades-Keyword-Researched = Researched
Hades-Keyword-Retaliate = Retaliate

Hades-Keyword-Road = Road
Hades-Keyword-Road-Format = Road {Amount:Word:Amount}

Hades-Keyword-Surge = Surge

Hades-Keyword-Swarming = Swarming
Hades-Keyword-Swarming-Format = Swarming {Amount:Word:Amount}

Hades-Keyword-Uses = Uses
Hades-Keyword-Uses-Format = Uses ({Amount:Word:Amount} {Type:Text:Type})

Hades-Keyword-Veiled = Veiled
