package com.mickeytheq.hades.strangeeons.util;

import com.google.common.base.Charsets;
import com.mickeytheq.hades.core.project.HadesProject;

import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;

public class ProjectUtils {
    // creates a Strange Eons project skeleton sufficient for the project to be recognised by the SE UI
    public static void createProjectSkeleton(Path projectRootDirectory) {
        try {
            Files.createDirectories(projectRootDirectory);
        } catch (IOException e) {
            throw new RuntimeException("Error creating root directory: " + projectRootDirectory, e);
        }

        Path seProjectPath = projectRootDirectory.resolve("seproject");

        if (!Files.exists(seProjectPath)) {
            // create a minimal se project file
            try (PrintWriter writer = new PrintWriter(Files.newBufferedWriter(seProjectPath, Charsets.UTF_8))) {
                writer.println("# Generated by hades");
                writer.println("type = PROJECT");
            } catch (IOException e) {
                throw new RuntimeException("Error creating seproject file at path '" + projectRootDirectory + "'", e);
            }
        }

        HadesProject.createProjectIfNotExists(projectRootDirectory);
    }
}
